object Versions {
    const val appCompat = "1.6.1"
    const val constraintLayout = "2.1.4"
    const val material = "1.9.0"
    const val coreKtx = "1.10.0"
    const val gson = "2.10.1"
    const val kotlin = "1.8.10"
    const val coroutines = "1.6.1"
    const val glide = "4.15.1"
    const val retrofit = "2.9.0"
    const val lifecycle = "2.6.1"
    const val testOrchestrator = "1.4.2"
    const val mockk = "1.13.5"
    const val koin = "3.4.0"
    const val navigation = "2.5.3"
}